### ISSUE TITLE
Citation is out of date

### ISSUE THREAD

**Issue by bwgref** [StingraySoftware/StingraySoftware.github.io#13]
Hey guys. Was doing some Stingray PR on the NuSTAR HEASARC page and noticed that the Stingray citation on the GitHub.io page might be out of date (it says "Submitted" instead of "Published in ApJ" or something).

I'm not sure if the 2019 paper is still the one that you want people to cite, but you may just want to update that section.

**Comment by matteobachetti** [comment]
Thanks @bwgref, I updated the citation :)

**Comment by matteobachetti** [comment]
The link to the Stingray documentation, in case you wanted that, is https://stingray.readthedocs.io (that points to https://stingraysoftware.github.io/stingray/ ) instead

**Comment by jdswinbank** [comment]
(This should have been closed by 896e339 but it wasn't!)
