### ISSUE TITLE
Offer: stingray domain

### ISSUE THREAD

**Issue by jdswinbank** [StingraySoftware/StingraySoftware.github.io#15]
Hi Stingray Team,

If you like, I will provide a domain name for stingray. I would suggest either:

- `stingray.software` or
- `stingray.science`

but I'm happy if you prefer something else as long as it's not too crazily expensive. I'll pay for the domain for the foreseeable future (_at a minimum_ the first year, and likely indefinitely... but that's a long time, so no promises).

I'll take care of registering the domain and configuring the website so that the content currently accessible at http://stingraysoftware.github.io/ becomes accessible at https://(your domain) and the main Stingray documentation becomes accessible at https://(yourdomain)/stingray (also happy to help with doing the same for DAVE & HENDRICS, but I don't know how their docs are set up so I'm not sure how easy it'd be).

I'd also be happy to handle mail arriving to addresses @(your domain). At a minimum, we can catch mail to (anything)@(your domain) and forward it to an address of your choosing. If you like, I can also set up individual redirects for (your name)@(your domain) and forward that wherever you like (but you should be aware that I could — in principle — intercept any mail en route, so you wouldn't want to use this for anything sensitive).

Please let me know if you're interested!

**Comment by matteobachetti** [comment]
Hi @jdswinbank, this looks like a great offer ;) 
HENDRICS's documentation is already in Sphinx format, and we are moving DAVE's documentation to the same framework, so I would also, not necessarily immediately, use the opportunity to put all docs under a common web domain
I would personally prefer stingray.science. 
@dhuppenkothen, @abigailStev, @smigliari, @pbalm?

**Comment by matteobachetti** [comment]
BTW, @jdswinbank: would you like to join our small but motivated group of maintainers, contributing to the bestestest spectral timing code in the world?

**Comment by jdswinbank** [comment]
Hey folks — with Daniela's encouragement, I went ahead and registered `stingray.science`. It's now set up so that:

- https://stingray.science is the main StingraySoftware landing page (ie, the content that was formerly at https://stingraysoftware.github.io)
- https://www.stingray.science and https://stingraysoftware.github.io (and the plain-old-http versions of the same) both redirect to the above.
- Mail sent to (anything) at stingray.science will come to me! :-)

I hope that works for you! I can easily tweak the mail set up so that:

- (anything) at stingray.science goes somewhere else (where?)
- (username) at stingray.science forwards to your personal address somewhere else

Please let me know if you'd like either of the above.

It'd be neat to make the Slack invitation system at https://stingray-slack.herokuapp.com appear at slack.stingray.science. In order to do that, I guess we need to log in to Heroku (just pointing a CNAME at it doesn't seem to be enough). If you'd like to do this, and you have the account details handy, give me a shout.

**Comment by jdswinbank** [comment]
Oh, and:

> BTW, @jdswinbank: would you like to join our small but motivated group of maintainers, contributing to the bestestest spectral timing code in the world?

I'm honoured! But I don't think I can promise to commit much time to Stingray at the moment. If my occasional spate of doc-fixing is worth being a maintainer, then sure, sign me up... :-)

**Comment by matteobachetti** [comment]
I think the Heroku app was set up by @swapsha96? Or maybe @OrkoHunter?

**Comment by OrkoHunter** [comment]
Found the SlackIn Heroku app https://stingray-slack.herokuapp.com on one of my Heroku accounts. 😄 (Added you @matteobachetti as a collaborator on the app).

I have added the domain `slack.stingray.science` on the Heroku app and it's asking to set the DNS target (I guess a CNAME record) `protected-whitefish-v77bt2r90njcpxreb79foxwt.herokudns.com` on the domain nameserver. Once that's added, I think http://slack.stingray.science will start to work.

<img width="1791" alt="Screenshot 2021-04-18 at 12 10 10 AM" src="https://user-images.githubusercontent.com/8065913/115123431-a67f9c80-9fda-11eb-858d-3d3df668783a.png">

**Comment by jdswinbank** [comment]
Thanks @OrkoHunter!

The good news is that https://slack.stingray.science is now up & running! 🎉 

The bad news is that I had to fudge things a little bit so we're not currently running in quite as secure a mode as I'd like. In order to fix that, we need to install an origin certificate on Heroku — see https://help.heroku.com/GVS2BTB5/why-am-i-getting-error-525-ssl-handshake-failed-with-cloudflare-when-using-a-herokudns-com-endpoint for details. Is one of you willing & able to help with that? Let me know and I'll send you the relevant cert by some more secure method than GitHub issue! 😁

**Comment by OrkoHunter** [comment]
Nice! The website seems to be working for me, even on HTTPS 😄 
<img width="1187" alt="Screenshot 2021-04-18 at 11 00 43 AM" src="https://user-images.githubusercontent.com/8065913/115135332-68fc2d00-a035-11eb-86ca-438cb79eb3c9.png">

**Comment by matteobachetti** [comment]
Thanks a lot @OrkoHunter and @jdswinbank! This simplifies things considerably!
@jdswinbank : what should I do to redirect hendrics.readthedocs.io and the equivalent DAVE page in preparation to stingray.science/packagename ?

**Comment by jdswinbank** [comment]
@matteobachetti — unfortunately, it doesn't look like readthedocs.org supports hosting documentation there while having the hostname be `stingray.science` (ie, having https://stingray.science/hendrics hosted on RtD seems to be impossible). I think there are two options:

1. Host the documentation at readthedocs.org and we can give it a hostname within `stingray.science`. For example, https://hendrics.stingray.science could refer to your RtD documentation.
2. Migrate away from reathedocs.org and build the documentation using GitHub Actions, like we do for Stingray itself. This would make URLs like http://stingray.science/hendrics possible.

Things to consider:

- The main advantage of RtD is that it makes it possible to simultaneously publish documentation for multiple releases of the code. For example, it will simultaneously host docs for all released versions of HENDRICS, plus `master`/`main` if you want. Doing this with GitHub Actions would be possible, but quite a bit more work.
- The main advantage of GitHub Actions (apart from consistency with Stingray) is that it is easier to understand and debug than RtD in my experience (others' mileage may vary!).
- If you wanted to use RtD for HENDRICS *and* keep consistent URLs for all the docs, we could change things around to publish the Stingray docs at some other hostname (e.g. at https://docs.stingray.science).

My suggestion would be to migrate to GitHub Actions for HENDRICS & DAVE docs, because I think it's simplest, but obviously it's your call!

**Comment by matteobachetti** [comment]
Hi @jdswinbank, thanks a lot for the thorough investigation.
In my opinion, hosting the docs for multiple versions is very useful. I wouldn't mind having stingray.science as a page with three boxes that point to, e.g., docs.stingray.science, hendrics.stingray.science, dave.stingray.science. Readthedocs is a little clunky sometimes, but has proven reliable. Also, I wouldn't want to put everything on a single platform (Github). I don't expect that Github will turn evil and will steal all our code and infrastructure for a ransom, but still...

No strong opinions, maybe @dhuppenkothen and @abigailStev want to chime in

**Comment by jdswinbank** [comment]
Hi @matteobachetti — if you follow steps 2 onwards (I've already done step 1) of the instructions at https://docs.readthedocs.io/en/stable/custom_domains.html#custom-domain-support you should be able to add the custom domain `hendrics.stingray.science` to your docs. Per that page, it might take an hour to get an SSL certificate generated, but then it should all just kick into life.

If that works for you, and assuming @dhuppenkothen and @abigailStev don't object, I can migrate the Stingray docs to follow a similar pattern. I didn't see any published docs for DAVE yet (did I miss them?) but it will be easy to use the same pattern for them when they're ready.

One of the advantages of Stingray having its own domain, of course, is that if GitHub does turn evil we should transparently be able to switch everything to alternative infrastructure — all we'll need is a recent clone of the source. 😁

**Comment by jdswinbank** [comment]
Since the `stingray.science` domain is now up and running, I think we can close this issue. I'll open a new issue on the HENDRICS repository to suggest making its documentation available at https://hendrics.stingray.science.

**Comment by jdswinbank** [comment]
https://github.com/StingraySoftware/HENDRICS/issues/101
